channels:
- defaults
- menpo
- conda-forge
- soft-matter
dependencies:
- ffmpeg
- av
- future
- numpy
- scipy
- ipython
- ipyparallel
- jupyter
- ipywidgets
- bqplot
- matplotlib
- scikit-image
- scikit-learn
- h5py
- nb_conda
- cython
- spyder
- nose
- bokeh
- tensorflow
- keras
- tqdm
- tifffile
- peakutils
- slicerator
- pims
- opencv3
- appmode
- jupyter_dashboards
#- pip:
#	- tifffile
# 	- peakutils
